opensearch-project/dashboards-visualizations

.github/workflows/release-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/.cypress/integration/ui.spec.js, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
- change plugin version to 1.0.0
=> Change plugin versions to 1.0.0

release-notes/opensearch-dashboards-visualizations.release-notes-1.0.0.0-beta1.md
Add release notes for OpenSearch beta release
=> Add release notes for opensearch beta release

.github/workflows/release-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json
Rename artifacts to follow camel case naming convention
=> Rename artifacts to follow camel case

README.md
Update docs link to opensearch. Gantt chart only depends on OpenSearch Dashboards API, so no additional plugin API renaming needed.
#10 
=> Update documentation link to opensearch

.github/workflows/release-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Update version to rc1

MAINTAINERS.md, README.md
Change copyright to OpenSearch Contributors in readme.md
#21 
=> Update copyright notice in readme

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json, release-notes/opensearch-dashboards-visualizations.release-notes-1.1.0.0.md
Bump version for opensearch 1.1.0 release
=> Bump version for opensearch 1.1.0 release

gantt-chart/package.json
=> [1.2] Force cypress to use PDT time (#41)

.github/workflows/test-and-build-workflow.yml
=> Fix UT coverage on codecov

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Bump gantt chart for 1.3 release

release-notes/opensearch-dashboards-visualizations.release-notes-1.3.0.0.md
Signed-off-by: Eugene Lee <eugenesk@amazon.com>
Add 1.3.0 release notes
=> Add 1.3.0 release notes

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Bump dashboards plugin to 1.3.1

gantt-chart/package.json, gantt-chart/yarn.lock
=> Remove duplicated dependencies

.github/draft-release-notes-config.yml, .github/workflows/draft-release-notes-workflow.yml, release-notes/opensearch-dashboards-visualizations.release-notes-2.0.0.0-rc1.md
=> Add release notes for 2.0.0-rc1

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.2.
Part of https://github.com/opensearch-project/opensearch-build/issues/1882
=> Incremented version to 1.3.2.

gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Remove rc1 qualifier for 2.0

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101
=> Version Increment to 1.3.3 OpenSearch Dashboard release

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
=> Incremented version to 2.0.1

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
version bump to 2.1.0
=> version bump to 2.1.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.1.0.0.md
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
Add 2.1 release notes
=> 2.1 release notes

release-notes/opensearch-dashboards-visualizations.release-notes-2.1.0.0.md
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
change 2.1 version bump PR under maintenance 
=> change 2.1 version bump PR under maintenance 

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
=> Incremented version to 1.3.4.

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
Bump up main to 3.0
#96 
=> Bump up main to 3.0

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: vamsi-amazon <reddyvam@amazon.com>
=> Bumping version to 2.2

release-notes/opensearch-dashboards-visualizations.release-notes-2.2.0.0.md
Signed-off-by: vamsi-amazon <reddyvam@amazon.com>
Release notes 2.2.0
=> Release notes for 2.2.0

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348
=> [Release 1.3.5] Version increment

gantt-chart/yarn.lock
=> Upgrade yarn dependencies for gantt-chart

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 2.2.1
Part of: https://github.com/opensearch-project/opensearch-build/issues/2481
=> Version increment 2.2.1

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Eric Wei <menwe@amazon.com>
Version bump for 2.3
=> 2.3 version bump

release-notes/opensearch-dashboards-visualizations.release-notes-2.3.0.0.md
Signed-off-by: Eric Wei <menwe@amazon.com>
Release notes for 2.3.0.
=> Release notes for 2.3.0

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json, release-notes/opensearch-dashboards-visualizations.release-notes-2.3.0.0.md
Manually backporting release notes to 2.3.
=> Backport/backport 112 to 2.3

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.3.1 to prepare for patch release
=> Bump version to 2.3.1

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Version bump to 1.3.6
Part of https://github.com/opensearch-project/opensearch-build/issues/2650
=> Version bump to 1.3.6

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Bump gantt chart to 2.4.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.4.0.0.md
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Release notes for 2.4.0
=> Release notes for 2.4.0

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Version bump to 1.3.7
=> Version bump to 1.3.7

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json, gantt-chart/yarn.lock
- Update 1.x with latest 1.3 branch
- Upgrade libraries for CVEs
=> [1.x] Bump node library versions

gantt-chart/yarn.lock
=> [Backport 1.3] Bump node library versions

gantt-chart/package.json, gantt-chart/yarn.lock
=> [1.3] Force ansi-regex to ^5.0.1

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.4.1
=> Bump version to 2.4.1

release-notes/opensearch-dashboards-visualizations.release-notes-1.3.7.0.md
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
Adding release notes for 1.3.7
=> Adding release notes for 1.3.7

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Bump version to 2.5.0
=> Bump version to 2.5.0

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Bump version to 1.3.8.  
=> Bump version to 1.3.8

.github/workflows/test-and-build-workflow.yml, gantt-chart/package.json, gantt-chart/yarn.lock, release-notes/opensearch-dashboards-visualizations.release-notes-1.3.7.0.md
Backport 1.3.7 changes to 1.x branch 
=> 1.3 release notes

gantt-chart/opensearch_dashboards.json
=> Make it compatible with OSD 2.4.1

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump to 2.4.2
=> Bump to 2.4.2

release-notes/opensearch-dashboards-visualizations.release-notes-2.5.0.0.md
=> [2.5] Add release notes for 2.5.0.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.5.0.0.md
=> [2.x] Add release notes for 2.5.0.0

gantt-chart/package.json, gantt-chart/yarn.lock
bump `glob-parent` and `debug` libraries
=> Force resolve `glob-parent` and `debug` libraries

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Bump gantt chart to 2.6.0 
=> Bump gantt chart to 2.6.0 

release-notes/opensearch-dashboards-visualizations.release-notes-2.6.0.0.md
Adding release notes for 2.6
#165
=> Adding release notes for 2.6

release-notes/opensearch-dashboards-visualizations.release-notes-2.6.0.0.md
Adding release notes for 2.6
(cherry picked from commit 9e1e6dc2899474f4a3b13b5cb1faf6d9c820b6e8)
Merge pull request #170 from ps48/release-2.6
#165
=> [Backport 2.6] add release notes for 2.6

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> version bump to 2.7.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.7.0.0.md
Add release notes for 2.7 release.
https://github.com/opensearch-project/dashboards-visualizations/issues/176
=> Add 2.7 release notes

release-notes/opensearch-dashboards-visualizations.release-notes-2.8.0.0.md
=> Add release notes for 2.8

release-notes/opensearch-dashboards-visualizations.release-notes-2.9.0.0.md
- Added release notes for 2.9.0
=> Add release notes for 2.9.0

gantt-chart/package.json, gantt-chart/yarn.lock
=> Fix 1.3 CVE

.github/workflows/backport.yml
=> update fail backport

release-notes/opensearch-dashboards-visualizations.release-notes-1.3.12.0.md
=> Add release notes for 1.3.12

gantt-chart/package.json, gantt-chart/yarn.lock
Upgrade requests to 3.0
fix CVE-2023-28155 
=> Add @cypress/request resolution to fix CVE-2023-28155 

gantt-chart/package.json, gantt-chart/yarn.lock
Upgrade requests to 3.0
Original PR: #245 
fix CVE-2023-28155
=> [Backport 2.x] Add @cypress/request resolution to fix CVE-2023-28155

release-notes/opensearch-dashboards-visualizations.release-notes-2.10.0.0.md
=> Add 2.10.0 release notes

gantt-chart/package.json, gantt-chart/yarn.lock
=> Upgrade cypress/request to version 3

release-notes/opensearch-dashboards-visualizations.release-notes-2.11.0.0.md
=> Maintenance/release notes 2.11

.github/workflows/ftr-e2e-gantt-chart-test.yml
Add FTR workflow for gantt chart plugin test
=> [CI/CD] Add FTR workflow for gantt chart plugin test

.github/workflows/ftr-e2e-gantt-chart-test.yml
Add FTR workflow for gantt chart plugin test
* Backport #306 
=> [Backport 2.x] Add FTR workflow for gantt chart plugin test

gantt-chart/package.json, gantt-chart/yarn.lock
Sync dependencies with latest versions
* Relate https://github.com/opensearch-project/dashboards-query-workbench/issues/240
=> Sync dependencies with latest versions

gantt-chart/package.json, gantt-chart/yarn.lock
Sync dependencies with its latest versions
* Backport https://github.com/opensearch-project/dashboards-visualizations/pull/310
=> [Backport 2.x] Sync dependencies with its latest versions

release-notes/opensearch-dashboards-visualizations.release-notes-2.12.0.0.md
Added release notes for 2.12
https://github.com/opensearch-project/dashboards-visualizations/issues/265
=> Added release notes for 2.12

package.json, yarn.lock
=> upgrade plotly to v2

package.json, yarn.lock
=> [1.3] upgrade plotly to v2

package.json, yarn.lock
=> [2.x] upgrade plotly to v2

package.json, yarn.lock
=> [2.12] upgrade plotly to v2

release-notes/opensearch-dashboards-visualizations.release-notes-2.13.0.0.md
Add release notes for 2.13
https://github.com/opensearch-project/dashboards-visualizations/issues/331
=> Add release notes for 2.13

release-notes/opensearch-dashboards-visualizations.release-notes-2.14.0.0.md
Adding 2.14.0 release notes
https://github.com/opensearch-project/dashboards-visualizations/issues/356
=> Adding 2.14.0 release notes

release-notes/opensearch-dashboards-visualizations.release-notes-2.15.0.0.md
Adding 2.15.0 release notes
https://github.com/opensearch-project/dashboards-visualizations/issues/366
=> Adding 2.15.0 release notes

release-notes/opensearch-dashboards-visualizations.release-notes-2.16.0.0.md
Adding 2.16.0 release notes 
https://github.com/opensearch-project/dashboards-visualizations/issues/374
=> Adding 2.16.0 release notes 

public/components/__tests__/__snapshots__/options_editor.test.tsx.snap
=> Update snapshots for OUI 1.10.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.17.0.0.md
Adding release notes for 2.17.0
https://github.com/opensearch-project/dashboards-visualizations/issues/384
=> Adding release notes for 2.17.0

release-notes/opensearch-dashboards-visualizations.release-notes-2.18.0.0.md
=> release notes v2.18.0

package.json, yarn.lock
=> [Backport 2.x] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#414)

yarn.lock
Updates cross-spawn dependency in yarn.lock 
=> [CVE-2024-21538] Update cross-spawn in yarn.lock

release-notes/opensearch-dashboards-visualizations.release-notes-2.19.0.0.md
Adding release notes for 2.19.0
https://github.com/opensearch-project/dashboards-visualizations/issues/401
=> Adding release notes for 2.19.0
