opensearch-project/dashboards-visualizations

.github/workflows/release-workflow.yml, .github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json
=> Bump Version to Beta1 for OpenSearch Release

.github/workflows/release-workflow.yml, .github/workflows/test-and-build-workflow.yml, release-notes/opensearch-dashboards-visualizations.release-notes-1.0.0.0-rc1.md
Add release notes for 1.0.0.0-rc1
Change core deps to 1.0 branch
=> Update version and release notes for version 1.0.0.0-rc1

gantt-chart/.cypress/integration/ui.spec.js, gantt-chart/.cypress/tsconfig.json, gantt-chart/.cypress/utils/constants.js, gantt-chart/cypress.json
Dump jaeger data needed to run cypress before other tests
=> Auto dump cypress test data

gantt-chart/package.json, gantt-chart/yarn.lock
Jest is already a dependency in dashboards core, removing it in gantt chart
=> Remove explicit jest dependency

.github/workflows/test-and-build-workflow.yml, gantt-chart/opensearch_dashboards.json, gantt-chart/package.json, release-notes/opensearch-dashboards-visualizations.release-notes-1.2.0.0.md
Signed-off-by: Miki <mehranb@amazon.com>
* Bumps plugin version to 1.2.0.0
* Bumps the OSD version to 1.2.0
Partly addresses #26 
=> Bump version for OpenSearch 1.2.0 release

.github/workflows/dco.yml
Signed-off-by: Miki <mehranb@amazon.com>
Adds DCO checking workflow on PRs to the repository
=> Add DCO checking workflow

gantt-chart/package.json
=> Force cypress to use PDT time

gantt-chart/opensearch_dashboards.json, gantt-chart/package.json, gantt-chart/public/components/__tests__/__snapshots__/gantt_chart.test.tsx.snap, gantt-chart/public/components/__tests__/__snapshots__/gantt_chart_editor.test.tsx.snap, gantt-chart/public/components/__tests__/__snapshots__/options_editor.test.tsx.snap, gantt-chart/public/components/__tests__/options_editor.test.tsx
=> Add alpha1 qualifiers for dashboards plugin

.github/workflows/test-and-build-workflow.yml
Signed-off-by: Derek Ho <dxho@amazon.com>
Enable windows and macos builds
#33, #34
=> feat: add support for windows and macos

gantt-chart/package.json, gantt-chart/yarn.lock
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Added ansi-regex to resolution for resolving CVE-2021-3807
[CVE-2021-3807](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)
=> Bump ansi-regex to 5.0.1

gantt-chart/package.json, gantt-chart/yarn.lock
(cherry picked from commit c2409bcec72b270f04fd7fe25a8c1105a25042a6)
=> [1.x] Force ansi-regex to ^5.0.1

gantt-chart/public/components/gantt_chart.tsx
Making sure that duration value is actually numeric before plotting the chart.
https://github.com/opensearch-project/dashboards-visualizations/issues/149
=> [FIX-149] Sanitise duration value

.github/workflows/test-and-build-workflow.yml
The GitHub workflow uses the engines from OSD incorrectly. This change fixes that.
=> Fix Node.js and Yarn installation in CI

gantt-chart/package.json, gantt-chart/yarn.lock
- Added tough-cookie v4.1.3 to resolution
CVE-2023-26136
=> Upgrade tough-cookie to fix CVE-2023-26136

gantt-chart/.babelrc
Deprecated dependencies:
- `@babel/plugin-proposal-class-properties`
- `@babel/plugin-proposal-object-rest-spread`
* Relate https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5428
* Resolve https://github.com/opensearch-project/dashboards-visualizations/issues/295
=> [Bug fix] Update the dependencies in `.babelrc`

.github/workflows/test-and-build-workflow.yml, gantt-chart/package.json, gantt-chart/public/index.scss
Adds new yarn lint:style script that runs Stylelint and runs it in the build and test workflow. This should help make sure new Sass isn't written with anti-patterns.
https://github.com/opensearch-project/dashboards-visualizations/pull/229
=> [Backport 2.x] Onboard Stylelint (#229)

.github/workflows/cypress-e2e-gantt-chart-test.yml
Add Cypress e2e workflow for gantt chart
* Relate  #296 
```
The response we got was:
Status: 406 - Not Acceptable
Headers: {
"content-type": "application/json; charset=utf-8",
"osd-name": "fv-az985-504",
"cache-control": "private, no-cache, no-store, must-revalidate",
"vary": "accept-encoding",
"content-encoding": "gzip",
"date": "Wed, 13 Dec 2023 23:40:25 GMT",
"connection": "keep-alive",
"keep-alive": "timeout=120",
"transfer-encoding": "chunked"
}
Body: {
"error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
"status": 406
}
```
Link: https://github.com/opensearch-project/dashboards-visualizations/actions/runs/7202310509/job/19620185810?pr=298#step:20:115
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> [CI/CD] Add Cypress e2e workflow for gantt chart

.github/workflows/cypress-e2e-gantt-chart-test.yml
Add Cypress e2e workflow for gantt chart
* Backport #298 
=> [Backport 2.x] Add Cypress e2e workflow for gantt chart

.github/workflows/lint.yml, gantt-chart/.cypress/.eslintrc.js, gantt-chart/.eslintignore, gantt-chart/.eslintrc.js, gantt-chart/.eslintrc.yaml, gantt-chart/package.json
=> [CI/CD] Add eslint workflow

.github/workflows/lint.yml, gantt-chart/.cypress/.eslintrc.js, gantt-chart/.eslintignore, gantt-chart/.eslintrc.js, gantt-chart/.eslintrc.yaml, gantt-chart/package.json
[Backport 2.x] Add eslint workflow
=> [Backport 2.x] Add eslint workflow

.github/workflows/cypress-e2e-gantt-chart-test.yml, .github/workflows/ftr-e2e-gantt-chart-test.yml, .github/workflows/lint.yml, .github/workflows/test-and-build-workflow.yml
On behalf of the change in dashboards core: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675. We need to add `--single-version=loose` flag during the bootstrap step in our CI to manipulate the behavior of single-version validation. 
* Resolve the CI failure: https://github.com/opensearch-project/dashboards-observability/actions/runs/7964135017/job/21741091909?pr=1447#step:16:231
=> [CI/CD] Add single version flag during bootstrap to fix version conflicts

.github/workflows/verify-binary-installation.yml
I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRI …
=> Add workflow to verify binary installation

public/components/__tests__/__snapshots__/gantt_chart_editor.test.tsx.snap, public/components/__tests__/__snapshots__/options_editor.test.tsx.snap, public/components/gantt_chart_editor.tsx, public/components/options_editor.tsx
Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.
=>  Use smaller and compressed varients of buttons and form components

.github/workflows/cypress-e2e-gantt-chart-test.yml, .github/workflows/ftr-e2e-gantt-chart-test.yml, .github/workflows/test-and-build-workflow.yml, package.json, yarn.lock
Downgrade cypress version to 12.17.4 to match Opensearch Dashboards and upgrade artifact action to v4
Visualizations plugin is failing in dashboards 2.19.0 distribution build because of different cypress versions:
```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
were found declared across different package.json files. Please consolidate
those to match across all package.json files. Different versions for the
same dependency is not supported.
If you have questions about this please reach out to the operations team.
The conflicting dependencies are:
cypress
12.17.4 => opensearch-dashboards
^13.6.0 => gantt-chart-dashboards
```
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Downgrade cypress to 12.17.4

.github/workflows/cypress-e2e-gantt-chart-test.yml, .github/workflows/ftr-e2e-gantt-chart-test.yml, .github/workflows/test-and-build-workflow.yml, package.json, yarn.lock
* downgrade cypress to 12.17.4
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* update artifact action to v4
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
---------
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit bb37b66a91ab29140d26bb12703611f9b8dfc797)
=> [Manual Backport 2.x] Downgrade cypress to 12.17.4 (#412)

package.json, yarn.lock
[[CVE-2024-21538](https://github.com/advisories/GHSA-3xgq-45jj-v275)] Bump cross-spawn  to 7.0.5
=> [CVE-2024-21538] Bump cross-spawn to 7.0.5

package.json, yarn.lock
Manual backport for #414 to 2.19
=> [Backport 2.19] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#414)
